from backend.models.categoria import Categoria
from backend.models.producto import Producto
from backend.models.proveedor import Proveedor
from backend.models.cliente import Cliente
from backend.models.producto_proveedor import ProductoProveedor
from backend.models.pedido import Pedido
from backend.models.detalles_pedido import DetallePedido
from backend.models.devoluciones import Devolucion
from backend.models.movimientos_inventario import MovimientoInventario